apiVersion: v1
kind: Namespace
metadata:
  name: completed-linkerd-job-cleaner
  annotations:
    linkerd.io/inject: enabled

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: completed-linkerd-job-cleaner
rules:
  - apiGroups: ['']
    resources: ['pods']
    verbs:     ['list', 'delete']
  - apiGroups: ['batch']
    resources: ['jobs']
    verbs:     ['delete']

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: completed-linkerd-job-cleaner
  namespace: completed-linkerd-job-cleaner

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: completed-linkerd-job-cleaner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: completed-linkerd-job-cleaner
subjects:
- kind: ServiceAccount
  name: completed-linkerd-job-cleaner
  namespace: completed-linkerd-job-cleaner

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: completed-linkerd-job-cleaner
  namespace: completed-linkerd-job-cleaner
spec:
  schedule: "15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: completed-linkerd-job-cleaner
            image: mdmoss/completed-linkerd-job-cleaner:1
          restartPolicy: Never
          serviceAccountName: completed-linkerd-job-cleaner
